# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.0.5.4
_src_path: gh:simetri-sinergi-id/ssi-addons-repo-template
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: true
odoo_version: 14.0
rebel_module_groups: []
repo_description: Mixin Object Repository
repo_name: Mixin Object
repo_slug: ssi-mixin
travis_apt_packages: []
travis_apt_sources: []
