import setuptools

with open('VERSION.txt', 'r') as f:
    version = f.read().strip()

setuptools.setup(
    name="odoo14-addons-open-synergy-ssi-mixin",
    description="Meta package for open-synergy-ssi-mixin Odoo addons",
    version=version,
    install_requires=[
        'odoo14-addon-ssi_accounting_entry_mixin',
        'odoo14-addon-ssi_backend_mixin',
        'odoo14-addon-ssi_company_currency_mixin',
        'odoo14-addon-ssi_currency_mixin',
        'odoo14-addon-ssi_custom_information_mixin',
        'odoo14-addon-ssi_data_requirement_mixin',
        'odoo14-addon-ssi_decorator',
        'odoo14-addon-ssi_duration_mixin',
        'odoo14-addon-ssi_field_date_callable_attribute',
        'odoo14-addon-ssi_localdict_mixin',
        'odoo14-addon-ssi_m2o_configurator_mixin',
        'odoo14-addon-ssi_master_data_mixin',
        'odoo14-addon-ssi_multiple_approval_mixin',
        'odoo14-addon-ssi_operating_unit_mixin',
        'odoo14-addon-ssi_partner_mixin',
        'odoo14-addon-ssi_policy_mixin',
        'odoo14-addon-ssi_pricelist_mixin',
        'odoo14-addon-ssi_print_mixin',
        'odoo14-addon-ssi_product_line_account_mixin',
        'odoo14-addon-ssi_product_line_mixin',
        'odoo14-addon-ssi_product_line_price_mixin',
        'odoo14-addon-ssi_qr_code_mixin',
        'odoo14-addon-ssi_reference_document_mixin',
        'odoo14-addon-ssi_related_attachment_mixin',
        'odoo14-addon-ssi_res_currency_m2o_configurator_mixin',
        'odoo14-addon-ssi_res_partner_bank_m2o_configurator_mixin',
        'odoo14-addon-ssi_res_partner_m2o_configurator_mixin',
        'odoo14-addon-ssi_res_users_m2o_configurator_mixin',
        'odoo14-addon-ssi_salesperson_mixin',
        'odoo14-addon-ssi_schema_parser_mixin',
        'odoo14-addon-ssi_sequence_mixin',
        'odoo14-addon-ssi_source_document_mixin',
        'odoo14-addon-ssi_state_change_constrain_mixin',
        'odoo14-addon-ssi_state_change_history_mixin',
        'odoo14-addon-ssi_status_check_mixin',
        'odoo14-addon-ssi_tag_mixin',
        'odoo14-addon-ssi_term_condition_mixin',
        'odoo14-addon-ssi_transaction_cancel_mixin',
        'odoo14-addon-ssi_transaction_confirm_mixin',
        'odoo14-addon-ssi_transaction_date_due_mixin',
        'odoo14-addon-ssi_transaction_date_duration_mixin',
        'odoo14-addon-ssi_transaction_done_mixin',
        'odoo14-addon-ssi_transaction_mixin',
        'odoo14-addon-ssi_transaction_open_mixin',
        'odoo14-addon-ssi_transaction_partner_mixin',
        'odoo14-addon-ssi_transaction_pricelist_mixin',
        'odoo14-addon-ssi_transaction_queue_cancel_mixin',
        'odoo14-addon-ssi_transaction_queue_done_mixin',
        'odoo14-addon-ssi_transaction_queue_mixin',
        'odoo14-addon-ssi_transaction_ready_mixin',
        'odoo14-addon-ssi_transaction_salesperson_mixin',
        'odoo14-addon-ssi_transaction_tax_address_mixin',
        'odoo14-addon-ssi_transaction_terminate_mixin',
        'odoo14-addon-ssi_transaction_total_mixin',
        'odoo14-addon-ssi_transaction_win_lost_mixin',
        'odoo14-addon-test_ssi_accounting_entry_mixin',
        'odoo14-addon-test_ssi_custom_information_mixin',
        'odoo14-addon-test_ssi_duration_mixin',
        'odoo14-addon-test_ssi_multiple_approval_mixin',
        'odoo14-addon-test_ssi_policy_mixin',
        'odoo14-addon-test_ssi_product_line_account_mixin',
        'odoo14-addon-test_ssi_product_line_mixin',
        'odoo14-addon-test_ssi_product_line_price_mixin',
        'odoo14-addon-test_ssi_related_attachment_mixin',
        'odoo14-addon-test_ssi_sequence_mixin',
        'odoo14-addon-test_ssi_state_change_constrain_mixin',
        'odoo14-addon-test_ssi_status_check_mixin',
        'odoo14-addon-test_ssi_transaction_mixin',
    ],
    classifiers=[
        'Programming Language :: Python',
        'Framework :: Odoo',
        'Framework :: Odoo :: 14.0',
    ]
)
